import { Headphones, Mail, Phone } from "lucide-react";

export const POLICY_FILTERS = {
  status: [
    { key: "all", label: "Semua", value: "Semua" },
    { key: "aktif", label: "Aktif", value: "Aktif" },
    { key: "berakhir", label: "Berakhir", value: "Berakhir" },
  ],
  category: [
    { key: "all", label: "Semua", icon: "\u{1F4CB}" },
    { key: "properti", label: "Properti", icon: "\u{1F3E0}" },
    { key: "mobil", label: "Mobil", icon: "\u{1F697}" },
    { key: "motor", label: "Motor", icon: "\u{1F6F5}" },
    { key: "personal", label: "Personal", icon: "\u{1F464}" },
    { key: "lainnya", label: "Lainnya", icon: "\u{1F4DC}" },
  ],
};

export const DEFAULT_POLICIES = [
  {
    id: "policy-home",
    category: "Hunian utama",
    product: "Asuransi Rumah Tinggal",
    objectName: "Rumah tinggal 2 lantai, Kebayoran Baru",
    policyNumber: "JSD-PROP-2026-100184",
    insuredValue: 1250000000,
    annualPremium: 3480000,
    paymentStatus: "Lunas",
    status: "Aktif",
    tone: "success",
    periodStart: "12 Apr 2025",
    periodEnd: "11 Apr 2026",
    benefits: ["Kebakaran", "Banjir", "Gempa bumi", "Kerusuhan"],
    claimChecklist: ["Foto area kerusakan", "Kronologi kejadian", "Daftar bagian terdampak", "Dokumen tambahan bila diminta surveyor"],
    documents: ["E-polis", "Schedule benefit", "Bukti bayar", "Endorsement"],
  },
  {
    id: "policy-car",
    category: "Kendaraan pribadi",
    product: "Comprehensive Kendaraan - Mobil",
    objectName: "Honda Brio RS 2023",
    policyNumber: "JSD-MTR-2026-220091",
    insuredValue: 228000000,
    annualPremium: 5260000,
    paymentStatus: "Lunas",
    status: "Aktif",
    tone: "success",
    periodStart: "08 Jan 2026",
    periodEnd: "07 Jan 2027",
    benefits: ["Kerusakan sendiri", "Tanggung jawab hukum", "Banjir dan angin topan"],
    claimChecklist: ["Foto kerusakan kendaraan", "Kronologi kejadian", "STNK atau data kendaraan", "Dokumen pihak ketiga bila ada"],
    documents: ["E-polis", "Kartu ringkasan polis", "Invoice", "Bukti bayar"],
  },
  {
    id: "policy-pa",
    category: "Perlindungan keluarga",
    product: "Personal Accident Family",
    objectName: "Perlindungan kecelakaan diri keluarga",
    policyNumber: "JSD-PA-2026-300044",
    insuredValue: 500000000,
    annualPremium: 940000,
    paymentStatus: "Metode Bayar Perlu Diperbarui",
    status: "Aktif",
    tone: "warning",
    periodStart: "01 Mar 2026",
    periodEnd: "28 Feb 2027",
    benefits: ["Meninggal dunia akibat kecelakaan", "Cacat tetap", "Biaya perawatan darurat"],
    claimChecklist: ["Kronologi kejadian", "Surat dokter atau resume medis", "Kuitansi biaya perawatan", "Dokumen identitas tertanggung"],
    documents: ["E-polis", "Ringkasan manfaat", "Invoice", "Riwayat pembayaran"],
  },
  {
    id: "policy-home-2024",
    category: "Riwayat hunian",
    product: "Asuransi Rumah Tinggal 2024",
    objectName: "Rumah tinggal lama, Bintaro Jaya",
    policyNumber: "JSD-PROP-2024-087512",
    insuredValue: 980000000,
    annualPremium: 3010000,
    paymentStatus: "Periode Berakhir",
    status: "Berakhir",
    tone: "default",
    periodStart: "12 Apr 2024",
    periodEnd: "11 Apr 2025",
    benefits: ["Kebakaran", "Banjir"],
    claimChecklist: ["Lihat polis baru bila ingin melanjutkan perlindungan.", "Riwayat dokumen masih bisa dilihat dari daftar dokumen utama."],
    documents: ["E-polis 2024", "Bukti bayar 2024"],
  },
];

export const DEFAULT_CLAIMS = [
  {
    id: "CLM-2602-8820",
    policyId: "policy-pa",
    title: "Biaya rawat inap kecelakaan",
    lossDate: "25 Feb 2026",
    reportedDate: "25 Feb 2026",
    status: "Dokumen kurang",
    tone: "danger",
    stage: 2,
    amount: "Rp 8.200.000",
    nextAction: "Unggah surat dokter dan kuitansi asli agar review bisa dilanjutkan.",
    dueLabel: "Butuh tindak lanjut hari ini",
    assignedTo: "Tim klaim personal accident",
    nextUpdate: "Setelah dokumen masuk, review berikutnya dikirim maksimal 1 x 24 jam kerja.",
    requiredDocs: ["Surat dokter", "Kuitansi asli", "KTP tertanggung"],
    history: [
      { date: "25 Feb 2026", text: "Laporan awal diterima." },
      { date: "26 Feb 2026", text: "Tim klaim meminta dokumen medis tambahan." },
    ],
    canUpload: true,
    settled: false,
  },
  {
    id: "CLM-2602-9981",
    policyId: "policy-car",
    title: "Kerusakan bemper depan",
    lossDate: "28 Feb 2026",
    reportedDate: "28 Feb 2026",
    status: "Sedang disurvei",
    tone: "warning",
    stage: 3,
    amount: "Rp 4.500.000",
    nextAction: "Tunggu hasil survei. Anda belum perlu mengirim dokumen tambahan.",
    dueLabel: "Update berikutnya paling lambat besok",
    assignedTo: "Claim Assessment Center",
    nextUpdate: "Hasil survei akan ditampilkan di portal dan dikirim ke email terdaftar.",
    requiredDocs: [],
    history: [
      { date: "28 Feb 2026", text: "Laporan klaim kendaraan diterima." },
      { date: "29 Feb 2026", text: "Jadwal survei dikonfirmasi." },
    ],
    canUpload: false,
    settled: false,
  },
  {
    id: "CLM-2512-0091",
    policyId: "policy-car",
    title: "Kehilangan sepeda motor",
    lossDate: "15 Des 2025",
    reportedDate: "15 Des 2025",
    status: "Selesai",
    tone: "success",
    stage: 4,
    amount: "Rp 21.000.000",
    nextAction: "Tidak ada tindakan lanjutan.",
    dueLabel: "Selesai",
    assignedTo: "Pembayaran klaim",
    nextUpdate: "Dana sudah ditransfer ke rekening tertanggung.",
    requiredDocs: [],
    history: [
      { date: "15 Des 2025", text: "Laporan awal diterima." },
      { date: "20 Des 2025", text: "Dokumen lengkap." },
      { date: "05 Jan 2026", text: "Pembayaran klaim dilakukan." },
    ],
    canUpload: false,
    settled: true,
  },
];

export const DEFAULT_BILLING_ITEMS = [
  {
    id: "INV-2604-1001",
    policyId: "policy-home",
    title: "Perpanjangan polis rumah tinggal",
    dueDate: "11 Apr 2026",
    amount: 3520000,
    status: "Perlu Dibayar",
    tone: "warning",
    method: "BCA Virtual Account",
    helper: "Bayar hari ini agar perpanjangan tidak tertunda.",
  },
  {
    id: "INV-2603-1007",
    policyId: "policy-pa",
    title: "Premi Personal Accident Family",
    dueDate: "01 Mar 2026",
    amount: 940000,
    status: "Metode Bayar Perlu Diperbarui",
    tone: "danger",
    method: "Kartu Tersimpan Perlu Diperbarui",
    helper: "Metode bayar lama tidak lagi valid.",
  },
];

export const DEFAULT_PRINT_REQUESTS = [
  {
    id: "PRN-2604-0001",
    policyId: "policy-home",
    requestedAt: "10 Apr 2026",
    status: "Diproses",
    deliveryAddress: "Jl. Jenderal Sudirman Kav. 1, Jakarta Pusat",
    helper: "Cetakan polis sedang disiapkan untuk dikirim ke alamat terdaftar.",
  },
];

export const DEFAULT_OFFICIAL_CONTACTS = [
  { label: "Contact Center", value: "1500-073", helper: "24 jam", href: "tel:1500073", icon: Phone },
  { label: "Layanan pelanggan", value: "care@jasindo.co.id", helper: "Email resmi", href: "mailto:care@jasindo.co.id", icon: Mail },
  { label: "Telepon kantor", value: "(021) 3924737", helper: "Graha Jasindo", href: "tel:+62213924737", icon: Headphones },
];
